/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gauravcoding.dto;
@org.apache.avro.specific.AvroGenerated
public enum OrderType implements org.apache.avro.generic.GenericEnumSymbol<OrderType> {
  BUY, SELL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderType\",\"namespace\":\"com.gauravcoding.dto\",\"symbols\":[\"BUY\",\"SELL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
